general {
    gaps_in = 2
    gaps_out = 2
    border_size = 2
    layout = master
    allow_tearing = false

    col.active_border = rgb(89b4fa) rgb(a6e3a1) 45deg   
    col.inactive_border = rgb(313244)                    
}

decoration {
    rounding = 6
    active_opacity = 1.0
    inactive_opacity = 0.9
    dim_inactive = true
    dim_strength = 0.1

    blur {
        enabled = true
        size = 8
        passes = 3
        new_optimizations = true
        special = true
        xray = true
    }

    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(1a1a1aee) 
        color_inactive = rgba(00000000)
    }
}

animations {
    enabled = true
    bezier = snap, 0.05, 0.9, 0.1, 1.1
    
    animation = windows, 1, 3, snap, slide
    animation = windowsOut, 1, 3, snap, slide
    animation = border, 1, 5, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 4, snap, slidevert
}

master {
    orientation = left
    mfact = 0.5
    new_on_top = true
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
}

xwayland {
    force_zero_scaling = true   # Set false if on 4K or mixed DPI
}

input {
    kb_layout = us
    follow_mouse = 1
    numlock_by_default = true
    sensitivity = 0

    touchpad {
        natural_scroll = false
    }
}

monitor = ,preferred,auto,auto
