[pyprland]
plugins = [
  "scratchpads"
]

[scratchpads.term]
animation = "fromTop"
command = "kitty --class kitty-dropterm"
class = "kitty-dropterm"
size = "75% 60%"

[scratchpads.chatgpt]
animation = "fromRight"
command = "chromium --class=chatgpt-app --app=https://chat.openai.com"
class = "chatgpt-app"
size = "75% 85%"

[scratchpads.gemini]
animation = "fromLeft"
command = "chromium --class=gemini-app --app=https://gemini.google.com/app"
class = "gemini-app"
size = "75% 85%"

