config_version = 13

[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    capsule_padding = 8.0
    capsule_thickness = 0.79999998584389687
    end = [ "cpu", "temp", "ram", "tray", "volume", "network", "notifications", "clipboard" ]
    font_family = "JetBrainsMono NF"
    font_weight = 600
    icon_color = "primary"
    margin_edge = 0
    margin_ends = 0
    padding = 0
    scale = 1.1000000089406967
    start = [ "launcher", "workspaces" ]
    thickness = 40
    widget_spacing = 1

[[control_center.shortcuts]]
type = "caffeine"

[[control_center.shortcuts]]
type = "nightlight"

[[control_center.shortcuts]]
type = "notification"

[desktop_widgets]
enabled = false

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 1081.0
    output = "HDMI-A-1"
    placement_height = 1200.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[shell]
font_family = "JetBrainsMono NF"
ui_scale = 1.1000000089406967

    [shell.panel]
    control_center_placement = "floating"
    polkit_placement = "attached"
    wallpaper_placement = "floating"

[theme]
builtin = "Tokyo-Night"
mode = "dark"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "qt" ]

[wallpaper]
directory = "/home/owlsly/.config/wallpapers"
fill_mode = "stretch"

    [wallpaper.default]
    path = "/home/owlsly/.config/wallpapers/dark-forest.jpg"

    [wallpaper.last]
    path = "/home/owlsly/.config/wallpapers/dark-forest.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/owlsly/.config/wallpapers/dark-forest.jpg"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/owlsly/.config/wallpapers/14. Catppuccin Mocha.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/10. Abyssal Wave.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/owlsly/.config/wallpapers/01. Rosé Pine.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/27. Catppuccin Mocha.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/32. Catppuccin Mocha.png"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/Bridge.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    builtin_palette = "Tokyo-Night"
    palette_source = "builtin"
    path = "/home/owlsly/.config/wallpapers/dark-forest.jpg"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/jinx-arcane-5k-y9-1920x1200.jpg"
    theme_mode = "auto"

    [[wallpaper.favorite]]
    path = "/home/owlsly/.config/wallpapers/wallhaven-og3p6m.jpg"
    theme_mode = "auto"

[widget.clock]
format = "{:%H:%M %a %e.%b}"

[widget.cpu]
display = "text"
visualization = "none"

[widget.cputemp]
display = "text"
stat = "cpu_temp"

[widget.launcher]
glyph = "menu-2"
scale = 1.1000000000000001

[widget.network]
show_label = false

[widget.ram]
display = "text"
visualization = "none"

[widget.temp]
display = "text"
visualization = "none"

[widget.workspaces]
hide_when_empty = true
labels_only_when_occupied = true
occupied_color = "tertiary"
scale = 1.1000000000000001